name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1. 저장소 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # 필요에 따라 Node 버전을 조정하세요.

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. 빌드 실행 (Rollup로 src 폴더 내 파일들을 빌드)
      - name: Build project
        run: npm run build

      # 5. 빌드 결과물인 dist 폴더 압축 (GitHub Release 첨부용)
      - name: Create zip archive of dist folder
        run: zip -r quick-sonic-worklet.zip dist

      # 6. Semantic Release 실행 (태그, changelog, GitHub Release, npm 배포까지 자동 처리)
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 자동 생성 토큰
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}            # NPM 배포용 토큰
        run: npx semantic-release
